name: C++ builder/compiler with Makefile

on: 
  push:
    paths:
      - ./Makefile
      - "src/main.cpp"
      - "src/*/*.cpp"
      - "src/*/*.h"
      - ".github/*/*.yml"

jobs:
  makefile-build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Get current time
      uses: 1466587594/get-current-time@v2
      id: get-time
      with:
        format: YYYYMMDD-HH
        utcOffset: "+00:00"

    - name: Checkout
      uses: actions/checkout@v2.0.0
      
    - name: Run make
      run: make
    
    - name: Upload binary file as artifact
      uses: actions/upload-artifact@v2
      with:
        name: MCEngine-${{ steps.get-time.outputs.time }}
        path: bin/

    - name: Upload makefile depend
      uses: actions/upload-artifact@v2
      with:
        name: depend-${{ steps.get-time.outputs.time }}
        path: ./.dependencies

    - name: Run make dist-clean to delete .dependencies and .o files
      run: make dist-clean