name: C++ builder/compiler with Makefile

on: 
  push:
    paths:
      - ./Makefile
      - "src/main.cpp"
      - "src/*/*.cpp"
      - "src/*/*.h"
      - ".github/*/*.yml"

jobs:
  makefile-build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Get Time
      id: get-time
      uses: nanzm/get-time-action@v1.0
      with:
        timeZone: 5
        format: 'YYYY-MM-DD-HH-mm-ss'

    - name: Checkout
      uses: actions/checkout@v2.0.0
      
    - name: Run make
      run: make
    
    - name: Upload binary file as artifact
      uses: actions/upload-artifact@v2
      with:
        name: MCEngine-${{ steps.get-time.outputs.time }}
        path: bin/

    - name: Upload makefile depend
      uses: actions/upload-artifact@v2
      with:
        name: depend-${{ steps.get-time.outputs.time }}
        path: ./.dependencies

    - name: Run make dist-clean to delete .dependencies and .o files
      run: make dist-clean