name: C++ linter with Uncrustify

on:
    push:
        paths:
            - "src/main.cpp"
            - "src/*/*.cpp"

jobs:
  cpp_style_check:
    runs-on: ubuntu-latest
    name: Check C++ Style
    steps:
    - name: Checkout this commit
      uses: actions/checkout@v2
    - name: Run style checks
      uses: coleaeason/actions-uncrustify@v1